language: ruby
rvm:
  - 2.2.4
cache: bundler
sudo: false
addons:
  postgresql: "9.3"
   apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9 # required to build some npm packages on travis

env:
  global:
    - RAILS_ENV=test
    - CXX=g++-4.9

install:
  - bundle install --without production
  - nvm install 6.4
  - nvm use 6.4
  - npm install
  - bin/rake db:setup
script:
  - npm run lint
  - rake
